exclude: [
  post.sh
  #, _posts/1900-01-01-000.md
]

future: true
markdown: kramdown
highlighter: rouge
permalink: /ep-:title
sass:
  sass_dir: css
  style: compressed

title: TeNoHiRa Logs
url: https://tenohira.github.io
author: shamison,yanagirinn, etc... 
description: ログ的雑談Podcast
description_long: アニメ、ゲーム、ITなどを中心に、意見をころころ変えて、TeNoHiRaを返しまくる人達のログ的雑談Podcast
keywords: anime,game,it,tenohira
email: tenohira.pod@gmail.com
